services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: horilla_web
    ports:
      - "127.0.0.1:8003:8000"
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    command: sh ./entrypoint.sh
    volumes:
      - ./horilla:/app/horilla
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bullseye
    container_name: horilla_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - horilla-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  horilla-data:
